apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-timeFactor-settings
spec:
  forms:
    - group: basic
      label: Basic
      formSchema:
        - $el: a
          attrs:
            href: "https://docs.lik.cc"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "查看 Ink SEO助手 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/time-factor/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "Halo交流群"
        - $el: img
          attrs:
            src: "https://www.lik.cc/upload/iShot_2025-03-03_16.03.00.png"
            width: "100px"
            height: "120px"
            style:
              margin-left: "80px"
        - $formkit: checkbox
          label: "Baidu"
          name: enableBaiduTimeFactor
          id: enableBaiduTimeFactor
          key: enableBaiduTimeFactor
          value: true
          help: "Baidu search engine series time factor"
        - $formkit: checkbox
          label: "OG Timer"
          name: enableOGTimeFactor
          id: enableOGTimeFactor
          key: enableOGTimeFactor
          value: true
          help: "Mainstream search engine series time factor"
        - $formkit: checkbox
          label: "Meta Timefactor"
          name: enableMetaTimeFactor
          id: enableMetaTimeFactor
          key: enableMetaTimeFactor
          value: true
          help: "Meta time factor"
        - $formkit: checkbox
          label: "Struture Data"
          name: enableStructuredData
          id: enableStructuredData
          key: enableStructuredData
          value: true
          help: "How search engines like Google and Bing obtain content information"
        - $formkit: attachment
          label: Cover
          name: defaultImage
          id: defaultImage
          key: defaultImage
          help: "Cover thumbnail"