apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-seoToolkit-settings
spec:
  forms:
    - group: basic
      label: "Basic Settings"
      formSchema:
        - $el: a
          attrs:
            href: "https://docs.lik.cc"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "View Ink SEO Assistant Help Documentation"
            - $el: img
              attrs:
                src: "/plugins/seo-toolkit/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "Halo Communication Group"
        - $el: img
          attrs:
            src: "https://www.lik.cc/upload/iShot_2025-03-03_16.03.00.png"
            width: "100px"
            height: "120px"
            style:
              margin-left: "80px"
        - $formkit: checkbox
          label: "Enable Baidu Time Factor"
          name: enableBaiduTimeFactor
          id: enableBaiduTimeFactor
          key: enableBaiduTimeFactor
          value: true
          help: "Baidu search engine series time factors"
        - $formkit: checkbox
          label: "Enable OG Time Factor"
          name: enableOGTimeFactor
          id: enableOGTimeFactor
          key: enableOGTimeFactor
          value: true
          help: "Mainstream search engine series time factors"
        - $formkit: checkbox
          label: "Enable Meta Time Factor"
          name: enableMetaTimeFactor
          id: enableMetaTimeFactor
          key: enableMetaTimeFactor
          value: true
          help: "Toutiao and other search engine series time factors"
        - $formkit: checkbox
          label: "Enable Structured Data"
          name: enableStructuredData
          id: enableStructuredData
          key: enableStructuredData
          value: true
          help: "How Google, Bing and other search engines obtain content information"
        - $formkit: checkbox
          label: "Enable Canonical Tag"
          name: enableCanonicalTag
          id: enableCanonicalTag
          key: enableCanonicalTag
          value: true
          help: "Add canonical URL meta tag to prevent duplicate content issues"
        - $formkit: checkbox
          label: "Enable Twitter Card"
          name: enableTwitterCard
          id: enableTwitterCard
          key: enableTwitterCard
          value: true
          help: "Add Twitter Card meta tags for better social media sharing"
        - $formkit: attachment
          label: "Default Cover Image"
          name: defaultImage
          id: defaultImage
          key: defaultImage
          help: "Used when no cover image is set"
        - $formkit: checkbox
          label: "Enable Meta Robots"
          name: enableMetaRobots
          id: enableMetaRobots
          key: enableMetaRobots
          value: true
          help: "Add robots meta tags for search engine indexing control"
        - $formkit: select
          label: "Robots Index Setting"
          name: robotsIndex
          id: robotsIndex
          key: robotsIndex
          value: "index"
          options:
            - label: "Index (allow indexing)"
              value: "index"
            - label: "No Index (prevent indexing)"
              value: "noindex"
          help: "Control whether search engines should index this content"
        - $formkit: select
          label: "Robots Follow Setting"
          name: robotsFollow
          id: robotsFollow
          key: robotsFollow
          value: "follow"
          options:
            - label: "Follow (follow links)"
              value: "follow"
            - label: "No Follow (don't follow links)"
              value: "nofollow"
          help: "Control whether search engines should follow links on this page"
        - $formkit: checkbox
          label: "Enable FAQ Schema"
          name: enableFAQSchema
          id: enableFAQSchema
          key: enableFAQSchema
          value: true
          help: "Generate FAQ structured data for Q&A content"
        - $formkit: checkbox
          label: "Enable How-To Schema"
          name: enableHowToSchema
          id: enableHowToSchema
          key: enableHowToSchema
          value: true
          help: "Generate How-To structured data for tutorial/guide content"
        - $formkit: combobox
          label: "Content Type Detection"
          name: contentTypeDetection
          id: contentTypeDetection
          key: contentTypeDetection
          value: "auto"
          options:
            - label: "Auto-detect"
              value: "auto"
            - label: "Manual override"
              value: "manual"
            - label: "Disabled"
              value: "disabled"
          help: "How to detect content types for structured data"
        - $formkit: checkbox
          label: "Enable Enhanced Social Media"
          name: enableEnhancedSocial
          id: enableEnhancedSocial
          key: enableEnhancedSocial
          value: true
          help: "Add enhanced social media meta tags for better sharing"
        - $formkit: checkbox
          label: "Enable LinkedIn Optimization"
          name: enableLinkedInTags
          id: enableLinkedInTags
          key: enableLinkedInTags
          value: true
          help: "Add LinkedIn-specific meta tags for professional sharing"
        - $formkit: checkbox
          label: "Enable Facebook Optimization"
          name: enableFacebookTags
          id: enableFacebookTags
          key: enableFacebookTags
          value: true
          help: "Add Facebook-specific meta tags for social sharing"
        - $formkit: select
          label: "Social Image Optimization"
          name: socialImageOptimization
          id: socialImageOptimization
          key: socialImageOptimization
          value: "auto"
          options:
            - label: "Auto-resize images"
              value: "auto"
            - label: "Use original images"
              value: "original"
            - label: "Disabled"
              value: "disabled"
          help: "Optimize images for social media platforms"
        - $formkit: checkbox
          label: "Enable Article Schema"
          name: enableArticleSchema
          id: enableArticleSchema
          key: enableArticleSchema
          value: true
          help: "Generate Article schema markup for rich snippets"
        - $formkit: select
          label: "Article Type"
          name: articleSchemaType
          id: articleSchemaType
          key: articleSchemaType
          value: "BlogPosting"
          options:
            - label: "BlogPosting"
              value: "BlogPosting"
            - label: "NewsArticle"
              value: "NewsArticle"
            - label: "TechArticle"
              value: "TechArticle"
            - label: "ScholarlyArticle"
              value: "ScholarlyArticle"
          help: "Schema.org article type for your content"
        - $formkit: text
          label: "Publisher Name"
          name: publisherName
          id: publisherName
          key: publisherName
          value: ""
          help: "Organization name for article publisher"
        - $formkit: checkbox
          label: "Include Breadcrumbs"
          name: includeBreadcrumbs
          id: includeBreadcrumbs
          key: includeBreadcrumbs
          value: true
          help: "Include breadcrumb navigation in article schema"
        - $formkit: checkbox
          label: "Estimate Reading Time"
          name: estimateReadingTime
          id: estimateReadingTime
          key: estimateReadingTime
          value: true
          help: "Estimate and include reading time in schema"
    - group: contentAnalysis
      label: "Content Analysis"
      formSchema:
        - $formkit: checkbox
          label: "Enable Content Analysis"
          name: enableContentAnalysis
          id: enableContentAnalysis
          key: enableContentAnalysis
          value: true
          help: "Enable content analysis and SEO suggestions"
        - $formkit: checkbox
          label: "Enable Keyword Density Analysis"
          name: enableKeywordDensity
          id: enableKeywordDensity
          key: enableKeywordDensity
          value: true
          help: "Analyze keyword density and provide optimization suggestions"
        - $formkit: checkbox
          label: "Enable Readability Score"
          name: enableReadabilityScore
          id: enableReadabilityScore
          key: enableReadabilityScore
          value: true
          help: "Calculate readability score using Flesch-Kincaid formula"
        - $formkit: checkbox
          label: "Enable Internal Linking Suggestions"
          name: enableInternalLinking
          id: enableInternalLinking
          key: enableInternalLinking
          value: true
          help: "Suggest internal links based on content analysis"
        - $formkit: checkbox
          label: "Enable Content Optimization"
          name: enableContentOptimization
          id: enableContentOptimization
          key: enableContentOptimization
          value: true
          help: "Provide content length and structure optimization suggestions"
    - group: technical
      label: "Technical SEO"
      formSchema:
        - $formkit: checkbox
          label: "Enable Technical SEO Audit"
          name: enableTechnicalAudit
          id: enableTechnicalAudit
          key: enableTechnicalAudit
          value: true
          help: "Enable automated technical SEO checks"
        - $formkit: checkbox
          label: "Enable Page Speed Monitoring"
          name: enablePageSpeed
          id: enablePageSpeed
          key: enablePageSpeed
          value: true
          help: "Monitor page speed and performance metrics"
        - $formkit: checkbox
          label: "Enable Mobile-Friendly Checks"
          name: enableMobileFriendly
          id: enableMobileFriendly
          key: enableMobileFriendly
          value: true
          help: "Check mobile-friendliness of pages"
        - $formkit: checkbox
          label: "Enable Broken Link Detection"
          name: enableBrokenLinks
          id: enableBrokenLinks
          key: enableBrokenLinks
          value: true
          help: "Detect and report broken links"
        - $formkit: checkbox
          label: "Enable Core Web Vitals"
          name: enableCoreWebVitals
          id: enableCoreWebVitals
          key: enableCoreWebVitals
          value: true
          help: "Monitor Core Web Vitals metrics"
    - group: imageOptimization
      label: "Image Optimization"
      formSchema:
        - $formkit: checkbox
          label: "Enable Image Optimization"
          name: enableImageOptimization
          id: enableImageOptimization
          key: enableImageOptimization
          value: true
          help: "Enable comprehensive image optimization features"
        - $formkit: checkbox
          label: "Enable Automatic Alt Text"
          name: enableAutoAltText
          id: enableAutoAltText
          key: enableAutoAltText
          value: true
          help: "Automatically generate SEO-friendly alt text for images"
        - $formkit: checkbox
          label: "Enable Image File Optimization"
          name: enableImageFileOptimization
          id: enableImageFileOptimization
          key: enableImageFileOptimization
          value: true
          help: "Optimize image file names for better SEO"
        - $formkit: checkbox
          label: "Enable Dynamic OG Images"
          name: enableDynamicOGImages
          id: enableDynamicOGImages
          key: enableDynamicOGImages
          value: true
          help: "Generate dynamic Open Graph images for social media"
        - $formkit: checkbox
          label: "Enable Lazy Loading"
          name: enableLazyLoading
          id: enableLazyLoading
          key: enableLazyLoading
          value: true
          help: "Implement lazy loading for improved page performance"
        - $formkit: text
          label: "AI Service API Key"
          name: aiServiceApiKey
          id: aiServiceApiKey
          key: aiServiceApiKey
          value: ""
          help: "API key for AI-powered alt text generation service"
        - $formkit: select
          label: "AI Service Provider"
          name: aiServiceProvider
          id: aiServiceProvider
          key: aiServiceProvider
          value: "openai"
          options:
            - label: "OpenAI"
              value: "openai"
            - label: "Google Vision AI"
              value: "google_vision"
            - label: "Azure Computer Vision"
              value: "azure_cv"
          help: "Choose AI service for image analysis and alt text generation"
        - $formkit: select
          label: "Image Quality"
          name: imageQuality
          id: imageQuality
          key: imageQuality
          value: "high"
          options:
            - label: "High (Best quality)"
              value: "high"
            - label: "Medium (Balanced)"
              value: "medium"
            - label: "Low (Smaller files)"
              value: "low"
          help: "Set image optimization quality level"
        - $formkit: text
          label: "OG Image Width"
          name: ogImageWidth
          id: ogImageWidth
          key: ogImageWidth
          value: "1200"
          help: "Width for generated Open Graph images (pixels)"
        - $formkit: text
          label: "OG Image Height"
          name: ogImageHeight
          id: ogImageHeight
          key: ogImageHeight
          value: "630"
          help: "Height for generated Open Graph images (pixels)"
        - $formkit: select
          label: "Lazy Loading Threshold"
          name: lazyLoadingThreshold
          id: lazyLoadingThreshold
          key: lazyLoadingThreshold
          value: "200"
          options:
            - label: "100px"
              value: "100"
            - label: "200px"
              value: "200"
            - label: "300px"
              value: "300"
            - label: "500px"
              value: "500"
          help: "Distance from viewport to start loading images (pixels)"
